### ISSUE TITLE
[UX] Views integration not required - should be removed

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/field_multiple_limit#6]
Views in Backdrop core seems to already provide settings for how many field values to display and also a value for offset, so this bit is not required and should be removed to avoid confusion:

<img width="985" alt="screen shot 2019-02-24 at 6 25 32 pm" src="https://user-images.githubusercontent.com/2423362/53296363-08f90a00-3862-11e9-95dd-3c6e2f11122e.png">

---
PR by @klonos: https://github.com/backdrop-contrib/field_multiple_limit/pull/7

**Comment by laryn** [comment]
Thanks.

**Comment by laryn** [comment]
This accidentally removed an important function which I've added back in https://github.com/backdrop-contrib/field_multiple_limit/commit/fcbb21d6b84a1bab2d6c3a45beb6e7c0592af955
